### ISSUE TITLE
Add tests

### ISSUE THREAD

**Issue by disba1ancer** [disba1ancer/dse#12]
- [ ] Add tests for functional.h
- [ ] Add tests for execution.h
- [ ] Add tests for coroutine,h
